# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'свойство',
                'verbose_name_plural': 'свойства',
                'default_related_name': 'properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='odinass.Property', verbose_name='родительская категория')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'значение свойства',
                'verbose_name_plural': 'значениея свойства',
                'default_related_name': 'property_values',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
    ]
