# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 21:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0002_auto_20170513_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=254, verbose_name='название')),
                ('article', models.CharField(blank=True, max_length=254, verbose_name='артикул')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='odinass.Category', verbose_name='категория')),
            ],
            options={
                'ordering': ['title'],
                'default_related_name': 'products',
                'verbose_name_plural': 'товары',
                'verbose_name': 'товар',
            },
        ),
        migrations.AlterField(
            model_name='propertyvalue',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_values', to='odinass.Property', verbose_name='свойство'),
        ),
        migrations.AddField(
            model_name='product',
            name='property_value',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='odinass.PropertyValue', verbose_name='значение свойства'),
        ),
    ]
