# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 21:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0003_auto_20170514_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='property_value',
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='odinass.Category', verbose_name='категории'),
        ),
        migrations.AddField(
            model_name='product',
            name='property_values',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='odinass.PropertyValue', verbose_name='значения свойства'),
        ),
    ]
