# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-13 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('odinass', '0004_auto_20170514_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='odinass.Category', verbose_name='категории'),
        ),
        migrations.AlterField(
            model_name='product',
            name='property_values',
            field=models.ManyToManyField(blank=True, related_name='products', to='odinass.PropertyValue', verbose_name='значения свойства'),
        ),
    ]
