# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 17:58
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_fsm
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('state', django_fsm.FSMField(choices=[('client_abort', 'отказ клиента'), ('for_payment', 'на оплату'), ('payed', 'оплачено клиентом'), ('waiting_for_approval', 'ждем подтверждения клиента'), ('waiting_for_parts', 'ждем запчасти'), ('without_repair', 'без ремонта'), ('working', 'в работе')], default='working', max_length=50, protected=True, verbose_name='статус')),
                ('client_name', models.CharField(help_text='Фамилия Имя Отчество', max_length=254, verbose_name='ФИО')),
                ('client_address', models.CharField(blank=True, max_length=254, verbose_name='адрес')),
                ('client_characteristic', models.CharField(blank=True, max_length=254, verbose_name='характеристика/внешний вид')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('client_phone', models.CharField(blank=True, max_length=254, verbose_name='телефон')),
                ('imei', models.CharField(blank=True, max_length=30, verbose_name='IMEI')),
                ('has_device', models.BooleanField(default=True, verbose_name='устройство')),
                ('has_battery', models.BooleanField(default=True, verbose_name='аккумулятор')),
                ('has_charger', models.BooleanField(default=False, verbose_name='зарядное устройство')),
                ('has_memory_card', models.BooleanField(default=False, verbose_name='карта памяти')),
                ('has_sim', models.BooleanField(default=False, verbose_name='SIM-карта')),
                ('has_bag_cover', models.BooleanField(default=False, verbose_name='сумка/чехол')),
                ('additional_kit', models.CharField(blank=True, max_length=254, verbose_name='дополнительно')),
                ('problem', models.TextField(verbose_name='неисправность')),
                ('note', models.CharField(blank=True, max_length=254, verbose_name='примечание')),
                ('estimated_date', models.DateField(verbose_name='предполагаемая дата готовности')),
                ('ready_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='дата готовности')),
                ('close_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='дата выдачи')),
                ('is_urgently', models.BooleanField(default=False, verbose_name='срочно')),
                ('estimated_cost', models.IntegerField(verbose_name='предполагаемая стоимость')),
                ('done_work', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='выполненная работа')),
            ],
            options={
                'verbose_name_plural': 'заявки',
                'default_related_name': 'bookings',
                'ordering': ['-pk'],
                'verbose_name': 'заявка',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='название')),
            ],
            options={
                'verbose_name_plural': 'бренды',
                'ordering': ['name'],
                'verbose_name': 'бренд',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=254, verbose_name='имя')),
                ('surname', models.CharField(max_length=254, verbose_name='фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=254, verbose_name='отчество')),
                ('address', models.CharField(blank=True, max_length=254, verbose_name='адрес')),
                ('characteristic', models.CharField(blank=True, max_length=254, verbose_name='характеристика')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=254, verbose_name='телефон')),
            ],
            options={
                'verbose_name_plural': 'клиенты',
                'ordering': ['surname', 'name', 'patronymic'],
                'verbose_name': 'клиент',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='наименование работы')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
            ],
            options={
                'verbose_name_plural': 'работы',
                'ordering': ['title'],
                'verbose_name': 'работа',
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='название')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.Brand', verbose_name='бренд')),
            ],
            options={
                'verbose_name_plural': 'модели',
                'ordering': ['name'],
                'verbose_name': 'модель',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.Brand', verbose_name='бренд'),
        ),
        migrations.AddField(
            model_name='booking',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.Client', verbose_name='клиент'),
        ),
        migrations.AddField(
            model_name='booking',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='crm.Model', verbose_name='модель'),
        ),
    ]
