# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 17:28
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='state',
            field=django_fsm.FSMField(default='new', max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_name',
            field=models.CharField(help_text='Фамилия Имя Отчество', max_length=254, verbose_name='ФИО'),
        ),
    ]
