# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django_fsm


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20170305_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='close_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='дата выдачи'),
        ),
        migrations.AddField(
            model_name='booking',
            name='ready_date',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='дата готовности'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='state',
            field=django_fsm.FSMField(choices=[('client_abort', 'отказ клиента'), ('for_payment', 'на оплату'), ('payed', 'оплачено клиентом'), ('waiting_for_approval', 'ждем подтверждения клиента'), ('waiting_for_parts', 'ждем запчасти'), ('without_repair', 'без ремонта'), ('working', 'в работе')], default='working', max_length=50, protected=True, verbose_name='статус'),
        ),
    ]
