# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170306_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='close_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='дата выдачи'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='ready_date',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='дата готовности'),
        ),
    ]
