# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20170504_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['name'], 'verbose_name': 'бренд', 'verbose_name_plural': 'бренды'},
        ),
        migrations.AlterModelOptions(
            name='model',
            options={'ordering': ['name'], 'verbose_name': 'модель', 'verbose_name_plural': 'модели'},
        ),
        migrations.AlterModelOptions(
            name='replacementdevice',
            options={'ordering': ['name'], 'verbose_name': 'устройство на замену', 'verbose_name_plural': 'устройства на замену'},
        ),
    ]
