# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 08:36
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20170307_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='done_work',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='выполненная работа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='client_characteristic',
            field=models.CharField(blank=True, max_length=254, verbose_name='характеристика/внешний вид'),
        ),
    ]
