# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20170310_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='наименование работы')),
                ('price', models.IntegerField(default=0, verbose_name='цена')),
            ],
            options={
                'ordering': ['title'],
                'verbose_name': 'работа',
                'verbose_name_plural': 'работы',
            },
        ),
    ]
